---
- hosts: leafs_DC1, leafs_DC2, DCIs
  gather_facts: no
  tasks:

  - name: Create template
    template:
      src: "{{lookup('env','PWD')}}/templates/delete_vlans.j2"
      dest: "{{lookup('env','PWD')}}/configs/{{inventory_hostname}}_no_vlans.cfg"

  - name: Upload config
    eos_config:
      src: "{{lookup('env','PWD')}}/configs/{{inventory_hostname}}_no_vlans.cfg"

